[project]
name = "scfitpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"

dependencies = ["numpy", "matplotlib", "scipy", "scikit-image", "opencv-python"]

[dependency-groups]
dev = ["h5py", "ipython", "jupyter", "pytest", "ruff", "tqdm", "jq"]
cupy = ["cupy"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
